version: '3'
services:
  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:latest
    restart: always
    network_mode: host
#    ports:
#      - "10051:10051"
    environment:
      - DB_SERVER_HOST=192.168.210.128
      - MYSQL_USER=zabbix
      - MYSQL_DATABASE=zabbix
      - MYSQL_PASSWORD=zabbix 
      - DB_SERVER_ROOT_USER=root
      - DB_SERVER_ROOT_PASS=123321
      - TZ＝'Asia/Shanghai'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./zabbix-scripts:/usr/lib/zabbix 
      - ./zabbixconfig:/etc/zabbix
  zabbix-web-nginx:
    image: zabbix/zabbix-web-nginx-mysql:latest
    restart: always
    network_mode: bridge
    ports:
      - "8080:80"
      - "8443:443"
    environment:
      - DB_SERVER_HOST=192.168.210.128
      - MYSQL_DATABASE=zabbix
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_ROOT_PASSWORD=123321
      - ZBX_SERVER_HOST=192.168.210.128
      - PHP_TZ="Asia/Shanghai"
      - TZ＝'Asia/Shanghai'
  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    environment:
      - ZBX_HOSTNAME=Zabbix server
      - ZBX_SERVER_HOST=127.0.0.1
      - ZBX_SERVER_PORT=10051
      - TZ='Asia/Shanghai'
    network_mode: host
#    ports:
#      - "10050:10050"
    restart: always
    privileged: true
#    links:
#      - zabbix-server:zabbixhost
