## ---------安装 openstack-neutron -----------
- name: Install openstack-neutron
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - openstack-neutron
    - openstack-neutron-ml2
    - openvswitch
    - openstack-neutron-openvswitch
    - ebtables

## ---------create neutron.conf -----------
- name: back old neutron.conf
  shell: "mv /etc/neutron/{{ item }}{,.bak}"
  with_items:
  - neutron.conf
  - l3_agent.ini
  - metadata_agent.ini
  - dhcp_agent.ini

- name: create neutron.conf
  template: src={{ item }} dest=/etc/neutron/{{ item }} mode=0755
  with_items:
  - neutron.conf
  - l3_agent.ini
  - metadata_agent.ini
  - dhcp_agent.ini

- name: change neutron.conf owner
  shell: "chown root.neutron /etc/neutron/{{ item }}"
  with_items:
  - neutron.conf
  - l3_agent.ini
  - metadata_agent.ini
  - dhcp_agent.ini

## ---------create openvswitch.conf -----------
- name: back old openvswitch.conf
  shell: "mv /etc/neutron/plugins/ml2/{{ item }}{,.bak}"
  with_items:
  - ml2_conf.ini
  - openvswitch_agent.ini

- name: create openvswitch.conf
  template: src={{ item }} dest=/etc/neutron/plugins/ml2/{{ item }} mode=0755
  with_items:
  - ml2_conf.ini
  - openvswitch_agent.ini

- name: change openvswitch.conf owner
  shell: "chown root.neutron /etc/neutron/plugins/ml2/{{ item }}"
  with_items:
  - ml2_conf.ini
  - openvswitch_agent.ini

## ---------create-neutron-plugin.ini -----------
- name: create-neutron-plugin.ini
  shell: "ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini"

## ---------load-neutron-database -----------
- name: load-neutron-cell0-database
  shell: "su -s /bin/sh -c \"neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head\" neutron"

## ---------restart-nova-api -----------
- name: restart-nova-api
  shell: "systemctl restart openstack-nova-api.service"

## ---------start neutron server-----------
- name: start neutron
  shell: "systemctl enable neutron-server.service \
    neutron-dhcp-agent.service \
    openvswitch neutron-openvswitch-agent \
    neutron-metadata-agent.service \
    && systemctl restart neutron-server.service \
    neutron-dhcp-agent.service \
    openvswitch neutron-openvswitch-agent \
    neutron-metadata-agent.service"

## ---------create externel bridge -----------
- name: create externel bridge
  shell: "ovs-vsctl add-br br-ex && ovs-vsctl add-port br-ex {{ externel_interface }} "

## ---------start neutron l3-agent-----------
- name: start neutron l3-agent
  shell: "systemctl enable neutron-l3-agent.service && systemctl start neutron-l3-agent.service"
