mysql:
    image: mariadb:latest
    ports:
        - "3306:3306"
    volumes:
        - ./mysqllib:/var/lib/mysql
        - ./mysqlconf:/etc/mysql
        - ./mysqllog:/var/log/mysql
    environment:
        - MYSQL_USER=zabbix
        - MYSQL_DATABASE=zabbix
        - MYSQL_PASSWORD=zabbix
        - MYSQL_ROOT_PASSWORD=123321
        - LANG=en_US.utf8
        - TZ=Asia/Shanghai
    restart: always
